name: demo
description: Demo program for jovial_svg

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  jovial_svg:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: "ROLLERBALL 1975"
        fonts:
          - asset: assets/fonts/rollerball.ttf
  assets:
    - assets/other/jupiter.si
    - assets/manifest.json
    - assets/svg/anglo.svg
    - assets/svg/anglo_bitmap.svg
    - assets/svg/bellot.svg
    - assets/svg/bonded.svg
    - assets/svg/dondorf.svg
    - assets/svg/gnomangelo.svg
    - assets/svg/gnomangelo_bitmap.svg
    - assets/svg/guyenne-classic.svg
    - assets/svg/layers.svg
    - assets/svg/nafo.svg
    - assets/svg/text_decoration.svg
    - assets/svg/ornamental.svg
    - assets/svg/paris-text.svg
    - assets/svg/paris.svg
    - assets/svg/swiss-xvii.svg
    - assets/svg/stylesheet.svg
    - assets/svg/svg11_gradient_1.svg
    - assets/svg/tango.svg
    - assets/svg/tiger.svg
    - assets/svg/tiny_07_12.svg
    - assets/svg/tiny_07_12_bbox01.svg
    - assets/svg/tiny_08_03.svg
    - assets/svg/tiny_08_03_cubic02.svg
    - assets/svg/tiny_09_02.svg
    - assets/svg/tiny_09_06.svg
    - assets/svg/tiny_11_01.svg
    - assets/svg/tiny_13_01.svg
    - assets/svg/tiny_13_02.svg
    - assets/svg/tiny_stroke_dasharray_1.svg
    - assets/svg/tiny_stroke_dasharray_2.svg
    - assets/svg/tiny_stroke_dasharray_3.svg
    - assets/svg/SVG_Logo.svg
    - assets/svg/mask1.svg
    - assets/svg/mask1luma.svg
    - assets/svg/mask2.svg
    - assets/svg/mask3.svg
    - assets/svg/mask4.svg
    - assets/svg/rainbow.svg
    - assets/svg/gradient_user_translate.svg
    - assets/svg/tspan.svg
    - assets/avd/anglo.xml
    - assets/avd/bellot.xml
    - assets/avd/bonded.xml
    - assets/avd/dondorf.xml
    - assets/avd/gnomangelo.xml
    - assets/avd/guyenne_classic.xml
    - assets/avd/ornamental.xml
    - assets/avd/paris.xml
    - assets/avd/paris_text.xml
    - assets/avd/rainbow.xml
    - assets/avd/svg11_gradient_1.xml
    - assets/avd/tango.xml
    - assets/si/anglo.si
    - assets/si/anglo_bitmap.si
    - assets/si/bellot.si
    - assets/si/bonded.si
    - assets/si/dondorf.si
    - assets/si/gnomangelo.si
    - assets/si/gnomangelo_bitmap.si
    - assets/si/layers.si
    - assets/si/nafo.si
    - assets/si/text_decoration.si
    - assets/si/guyenne-classic.si
    - assets/si/ornamental.si
    - assets/si/paris-text.si
    - assets/si/paris.si
    - assets/si/svg11_gradient_1.si
    - assets/si/swiss-xvii.si
    - assets/si/stylesheet.si
    - assets/si/tango.si
    - assets/si/tiger.si
    - assets/si/tiny_07_12.si
    - assets/si/tiny_07_12_bbox01.si
    - assets/si/tiny_08_03.si
    - assets/si/tiny_08_03_cubic02.si
    - assets/si/tiny_09_02.si
    - assets/si/tiny_09_06.si
    - assets/si/tiny_11_01.si
    - assets/si/tiny_13_01.si
    - assets/si/tiny_13_02.si
    - assets/si/tiny_stroke_dasharray_1.si
    - assets/si/tiny_stroke_dasharray_2.si
    - assets/si/tiny_stroke_dasharray_3.si
    - assets/si/SVG_Logo.si
    - assets/si/mask1.si
    - assets/si/mask1luma.si
    - assets/si/mask2.si
    - assets/si/mask3.si
    - assets/si/mask4.si
    - assets/si/rainbow.si
    - assets/si/gradient_user_translate.si
    - assets/si/tspan.si
